apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: visage-api
  namespace: visage
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: visage
    release: observability-monitoring-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/part-of: visage
  namespaceSelector:
    matchNames:
      - visage
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
